<script>
  import ParameterPanel from './lib/ParameterPanel.svelte';
  import SimulationViewport from './lib/SimulationViewport.svelte';
  import PromptBar from './lib/PromptBar.svelte';

  // State
  let simulationCode = ""; // Empty string means no simulation generated yet
  let isGenerating = false;
  let errorMessage = "";
  
  // These are dynamically generated by the AI based on the prompt
  let parameterDefs = [];
  
  // The actual values bound to the sliders
  let parameters = {};

  async function handlePromptSubmit(event) {
    const prompt = event.detail.prompt;
    console.log("Generating simulation for:", prompt);
    
    isGenerating = true;
    errorMessage = "";

    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        const errData = await response.json().catch(() => ({ error: 'Unknown error' }));
        throw new Error(errData.error || `Server error: ${response.status}`);
      }

      const data = await response.json();
      
      // Clear previous simulation state
      if (window.simState) {
        window.simState = null;
      }

      simulationCode = data.code;
      parameterDefs = data.parameterDefs || [];
      parameters = data.defaults || {};

    } catch (err) {
      console.error("Generation failed:", err);
      errorMessage = err.message;
      // Clear error after 5 seconds
      setTimeout(() => { errorMessage = ""; }, 5000);
    } finally {
      isGenerating = false;
    }
  }
</script>

<main class="app-layout">
  <!-- Top Header / Branding -->
  <header class="top-bar">
    <div class="logo">
      <span class="gradient-text">AI2Sim</span>
    </div>
  </header>

  <div class="content-area">
    <!-- Left: Main Viewport (Simulation + Prompt) -->
    <div class="main-stage">
      <SimulationViewport bind:parameters {simulationCode} />
      
      {#if errorMessage}
        <div class="error-toast">
          <span>⚠️ {errorMessage}</span>
        </div>
      {/if}

      <PromptBar on:submit={handlePromptSubmit} {isGenerating} />
    </div>

    <!-- Right: Parameter Controls Sidebar -->
    <ParameterPanel {parameterDefs} bind:parameters />
  </div>
</main>

<style>
  .app-layout {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
  }

  .top-bar {
    height: 60px;
    background-color: rgba(26, 26, 36, 0.85);
    backdrop-filter: blur(10px);
    border-bottom: 1px solid var(--border-color);
    box-shadow: var(--shadow-sm);
    display: flex;
    align-items: center;
    padding: 0 24px;
    z-index: 30;
  }

  .logo {
    font-size: 1.5rem;
    font-weight: 800;
    letter-spacing: -0.5px;
  }

  .gradient-text {
    background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    filter: drop-shadow(0 0 8px rgba(99, 102, 241, 0.5));
  }

  .content-area {
    display: flex;
    flex: 1;
    overflow: hidden;
  }

  .main-stage {
    flex: 1;
    position: relative;
    padding: 20px;
    display: flex;
    flex-direction: column;
  }

  .error-toast {
    position: absolute;
    top: 30px;
    left: 50%;
    transform: translateX(-50%);
    background: rgba(239, 68, 68, 0.9);
    backdrop-filter: blur(8px);
    color: white;
    padding: 12px 24px;
    border-radius: 12px;
    font-size: 0.9rem;
    z-index: 50;
    box-shadow: 0 4px 20px rgba(239, 68, 68, 0.3);
    animation: slideDown 0.3s ease-out;
  }

  @keyframes slideDown {
    from { opacity: 0; transform: translateX(-50%) translateY(-10px); }
    to { opacity: 1; transform: translateX(-50%) translateY(0); }
  }
</style>
