<script>
  import ParameterPanel from './lib/ParameterPanel.svelte';
  import SimulationViewport from './lib/SimulationViewport.svelte';
  import PromptBar from './lib/PromptBar.svelte';

  // State
  let simulationCode = ""; // Empty string means no simulation generated yet
  
  // These would be dynamically generated by the AI based on the prompt
  let parameterDefs = [];
  
  // The actual values bound to the sliders
  let parameters = {};

  function handlePromptSubmit(event) {
    const prompt = event.detail.prompt;
    console.log("Generating simulation for:", prompt);
    
    // MOCK GENERATION: 
    // In a real app, we would send 'prompt' to backend, get JS code and parameter defs back.
    // Here we just mock setting a particle simulation.
    setTimeout(() => {
      simulationCode = "// Mock generated simulation code runs here";
      
      // AI decided these are the adjustable parameters for this simulation
      parameterDefs = [
        { name: 'count', label: 'Particle Count', min: 10, max: 200, step: 1 },
        { name: 'speed', label: 'Speed Multiplier', min: 0.1, max: 5, step: 0.1 },
        { name: 'size', label: 'Size Multiplier', min: 0.5, max: 3, step: 0.1 }
      ];

      // Initialize default values
      parameters = {
        count: 50,
        speed: 1,
        size: 1
      };
    }, 1500); // Wait for mock generation to finish
  }
</script>

<main class="app-layout">
  <!-- Top Header / Branding -->
  <header class="top-bar">
    <div class="logo">
      <span class="gradient-text">AI2Sim</span>
    </div>
  </header>

  <div class="content-area">
    <!-- Left: Main Viewport (Simulation + Prompt) -->
    <div class="main-stage">
      <SimulationViewport bind:parameters {simulationCode} />
      <PromptBar on:submit={handlePromptSubmit} />
    </div>

    <!-- Right: Parameter Controls Sidebar -->
    <ParameterPanel {parameterDefs} bind:parameters />
  </div>
</main>

<style>
  .app-layout {
    display: flex;
    flex-direction: column;
    height: 100vh;
    width: 100vw;
  }

  .top-bar {
    height: 60px;
    background-color: rgba(26, 26, 36, 0.85);
    backdrop-filter: blur(10px);
    border-bottom: 1px solid var(--border-color);
    box-shadow: var(--shadow-sm);
    display: flex;
    align-items: center;
    padding: 0 24px;
    z-index: 30;
  }

  .logo {
    font-size: 1.5rem;
    font-weight: 800;
    letter-spacing: -0.5px;
  }

  .gradient-text {
    background: linear-gradient(135deg, var(--accent-primary), var(--accent-secondary));
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    filter: drop-shadow(0 0 8px rgba(99, 102, 241, 0.5));
  }

  .content-area {
    display: flex;
    flex: 1;
    overflow: hidden;
  }

  .main-stage {
    flex: 1;
    position: relative;
    padding: 20px;
    display: flex;
    flex-direction: column;
  }
</style>
